#!/bin/bash
# Copyright 2021
# Author: Tarek Allam Jr.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -o pipefail -e
SECONDS=0 # https://stackoverflow.com/a/8903280/4521950
python -c "import astronet as asn; print(asn.__version__)"

architecture="atx"
dataset="plasticc"
model="9879033-1641148336-0.1.dev938+g1cf0a82.d20220102"

python $ASNWD/sbin/evaluate_on_plasticc_test_set.py \
    --architecture $architecture \
    --dataset $dataset \
    --model $model \
    --redshift "" # With or without redshift. Remove argument if without

duration=$SECONDS
echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed."
