#!/bin/bash
# Copyright 2020
# Author: Tarek Allam Jr.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#SBATCH --job-name=evtests              # Job name
#SBATCH --time=48:00:00                 # Time limit hrs:min:sec
#SBATCH --output=logs/%j.log            # Standard output and error log
#SBATCH --exclusive                     # Request exclusive access to a node
#SBATCH --cpus-per-task=24              # Number of CPUs per node
# Add a -e or --error with an error file name to separate output and error
# logs. Note this will ignore the --output option if used afterwards
## #SBATCH -e logs/%j.err
## #SBATCH -o logs/%j.out
set -o pipefail -e
# source /share/hypatia/tallam/astronet/conf/astronet.conf
export ASNWD=/share/hypatia/tallam/astronet
# Print the contents of this file to stdout from line 15 onwards
awk 'NR>15' $ASNWD/sbin/evaluate-on-plasticc-test-set
SECONDS=0 # https://stackoverflow.com/a/8903280/4521950
# conda install -c conda-forge sncosmo
# pip install -r requirements.txt
which python
# pip install latex
export PATH="/home/tallam/texlive/2020/bin/x86_64-linux:$PATH"
# Test Imports
python -c "import astronet as asn; print(asn.__version__)"

python $ASNWD/sbin/evaluate_on_plasticc_test_set.py \
    --architecture $architecture \
    --dataset $dataset \
    --model $model
    # --redshift "" # With or without redshift. Remove argument if without

duration=$SECONDS
echo "$(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed."
