# Copyright 2020 - 2022
# Author: Tarek Allam Jr.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import numpy as np

from astronet.constants import ASTRONET_WORKING_DIRECTORY as asnwd

batch_filename = [
    "plasticc_test_lightcurves_02_chunk_0",
    "plasticc_test_lightcurves_02_chunk_1",
    "plasticc_test_lightcurves_02_chunk_2",
    "plasticc_test_lightcurves_02_chunk_3",
    "plasticc_test_lightcurves_02_chunk_4",
    "plasticc_test_lightcurves_02_chunk_5",
    "plasticc_test_lightcurves_02_chunk_6",
    "plasticc_test_lightcurves_02_chunk_7",
    "plasticc_test_lightcurves_02_chunk_8",
    "plasticc_test_lightcurves_02_chunk_9",
    "plasticc_test_lightcurves_02_chunk_10",
    "plasticc_test_lightcurves_02_chunk_11",
    "plasticc_test_lightcurves_02_chunk_12",
    "plasticc_test_lightcurves_02_chunk_13",
    "plasticc_test_lightcurves_02_chunk_14",
    "plasticc_test_lightcurves_02_chunk_15",
    "plasticc_test_lightcurves_02_chunk_16",
    "plasticc_test_lightcurves_02_chunk_17",
    "plasticc_test_lightcurves_02_chunk_18",
    "plasticc_test_lightcurves_02_chunk_19",
    "plasticc_test_lightcurves_02_chunk_20",
    "plasticc_test_lightcurves_02_chunk_21",
    "plasticc_test_lightcurves_02_chunk_22",
    "plasticc_test_lightcurves_02_chunk_23",
    "plasticc_test_lightcurves_02_chunk_24",
    "plasticc_test_lightcurves_02_chunk_25",
    "plasticc_test_lightcurves_02_chunk_26",
    "plasticc_test_lightcurves_02_chunk_27",
    "plasticc_test_lightcurves_02_chunk_28",
    "plasticc_test_lightcurves_02_chunk_29",
    "plasticc_test_lightcurves_02_chunk_30",
    "plasticc_test_lightcurves_02_chunk_31",
    "plasticc_test_lightcurves_02_chunk_32",
    "plasticc_test_lightcurves_02_chunk_33",
    "plasticc_test_lightcurves_02_chunk_34",
    "plasticc_test_lightcurves_03_chunk_0",
    "plasticc_test_lightcurves_03_chunk_1",
    "plasticc_test_lightcurves_03_chunk_2",
    "plasticc_test_lightcurves_03_chunk_3",
    "plasticc_test_lightcurves_03_chunk_4",
    "plasticc_test_lightcurves_03_chunk_5",
    "plasticc_test_lightcurves_03_chunk_6",
    "plasticc_test_lightcurves_03_chunk_7",
    "plasticc_test_lightcurves_03_chunk_8",
    "plasticc_test_lightcurves_03_chunk_9",
    "plasticc_test_lightcurves_03_chunk_10",
    "plasticc_test_lightcurves_03_chunk_11",
    "plasticc_test_lightcurves_03_chunk_12",
    "plasticc_test_lightcurves_03_chunk_13",
    "plasticc_test_lightcurves_03_chunk_14",
    "plasticc_test_lightcurves_03_chunk_15",
    "plasticc_test_lightcurves_03_chunk_16",
    "plasticc_test_lightcurves_03_chunk_17",
    "plasticc_test_lightcurves_03_chunk_18",
    "plasticc_test_lightcurves_03_chunk_19",
    "plasticc_test_lightcurves_03_chunk_20",
    "plasticc_test_lightcurves_03_chunk_21",
    "plasticc_test_lightcurves_03_chunk_22",
    "plasticc_test_lightcurves_03_chunk_23",
    "plasticc_test_lightcurves_03_chunk_24",
    "plasticc_test_lightcurves_03_chunk_25",
    "plasticc_test_lightcurves_03_chunk_26",
    "plasticc_test_lightcurves_03_chunk_27",
    "plasticc_test_lightcurves_03_chunk_28",
    "plasticc_test_lightcurves_03_chunk_29",
    "plasticc_test_lightcurves_03_chunk_30",
    "plasticc_test_lightcurves_03_chunk_31",
    "plasticc_test_lightcurves_03_chunk_32",
    "plasticc_test_lightcurves_03_chunk_33",
    "plasticc_test_lightcurves_03_chunk_34",
    "plasticc_test_lightcurves_04_chunk_0",
    "plasticc_test_lightcurves_04_chunk_1",
    "plasticc_test_lightcurves_04_chunk_2",
    "plasticc_test_lightcurves_04_chunk_3",
    "plasticc_test_lightcurves_04_chunk_4",
    "plasticc_test_lightcurves_04_chunk_5",
    "plasticc_test_lightcurves_04_chunk_6",
    "plasticc_test_lightcurves_04_chunk_7",
    "plasticc_test_lightcurves_04_chunk_8",
    "plasticc_test_lightcurves_04_chunk_9",
    "plasticc_test_lightcurves_04_chunk_10",
    "plasticc_test_lightcurves_04_chunk_11",
    "plasticc_test_lightcurves_04_chunk_12",
    "plasticc_test_lightcurves_04_chunk_13",
    "plasticc_test_lightcurves_04_chunk_14",
    "plasticc_test_lightcurves_04_chunk_15",
    "plasticc_test_lightcurves_04_chunk_16",
    "plasticc_test_lightcurves_04_chunk_17",
    "plasticc_test_lightcurves_04_chunk_18",
    "plasticc_test_lightcurves_04_chunk_19",
    "plasticc_test_lightcurves_04_chunk_20",
    "plasticc_test_lightcurves_04_chunk_21",
    "plasticc_test_lightcurves_04_chunk_22",
    "plasticc_test_lightcurves_04_chunk_23",
    "plasticc_test_lightcurves_04_chunk_24",
    "plasticc_test_lightcurves_04_chunk_25",
    "plasticc_test_lightcurves_04_chunk_26",
    "plasticc_test_lightcurves_04_chunk_27",
    "plasticc_test_lightcurves_04_chunk_28",
    "plasticc_test_lightcurves_04_chunk_29",
    "plasticc_test_lightcurves_04_chunk_30",
    "plasticc_test_lightcurves_04_chunk_31",
    "plasticc_test_lightcurves_04_chunk_32",
    "plasticc_test_lightcurves_04_chunk_33",
    "plasticc_test_lightcurves_04_chunk_34",
    "plasticc_test_lightcurves_05_chunk_0",
    "plasticc_test_lightcurves_05_chunk_1",
    "plasticc_test_lightcurves_05_chunk_2",
    "plasticc_test_lightcurves_05_chunk_3",
    "plasticc_test_lightcurves_05_chunk_4",
    "plasticc_test_lightcurves_05_chunk_5",
    "plasticc_test_lightcurves_05_chunk_6",
    "plasticc_test_lightcurves_05_chunk_7",
    "plasticc_test_lightcurves_05_chunk_8",
    "plasticc_test_lightcurves_05_chunk_9",
    "plasticc_test_lightcurves_05_chunk_10",
    "plasticc_test_lightcurves_05_chunk_11",
    "plasticc_test_lightcurves_05_chunk_12",
    "plasticc_test_lightcurves_05_chunk_13",
    "plasticc_test_lightcurves_05_chunk_14",
    "plasticc_test_lightcurves_05_chunk_15",
    "plasticc_test_lightcurves_05_chunk_16",
    "plasticc_test_lightcurves_05_chunk_17",
    "plasticc_test_lightcurves_05_chunk_18",
    "plasticc_test_lightcurves_05_chunk_19",
    "plasticc_test_lightcurves_05_chunk_20",
    "plasticc_test_lightcurves_05_chunk_21",
    "plasticc_test_lightcurves_05_chunk_22",
    "plasticc_test_lightcurves_05_chunk_23",
    "plasticc_test_lightcurves_05_chunk_24",
    "plasticc_test_lightcurves_05_chunk_25",
    "plasticc_test_lightcurves_05_chunk_26",
    "plasticc_test_lightcurves_05_chunk_27",
    "plasticc_test_lightcurves_05_chunk_28",
    "plasticc_test_lightcurves_05_chunk_29",
    "plasticc_test_lightcurves_05_chunk_30",
    "plasticc_test_lightcurves_05_chunk_31",
    "plasticc_test_lightcurves_05_chunk_32",
    "plasticc_test_lightcurves_05_chunk_33",
    "plasticc_test_lightcurves_05_chunk_34",
    "plasticc_test_lightcurves_06_chunk_0",
    "plasticc_test_lightcurves_06_chunk_1",
    "plasticc_test_lightcurves_06_chunk_2",
    "plasticc_test_lightcurves_06_chunk_3",
    "plasticc_test_lightcurves_06_chunk_4",
    "plasticc_test_lightcurves_06_chunk_5",
    "plasticc_test_lightcurves_06_chunk_6",
    "plasticc_test_lightcurves_06_chunk_7",
    "plasticc_test_lightcurves_06_chunk_8",
    "plasticc_test_lightcurves_06_chunk_9",
    "plasticc_test_lightcurves_06_chunk_10",
    "plasticc_test_lightcurves_06_chunk_11",
    "plasticc_test_lightcurves_06_chunk_12",
    "plasticc_test_lightcurves_06_chunk_13",
    "plasticc_test_lightcurves_06_chunk_14",
    "plasticc_test_lightcurves_06_chunk_15",
    "plasticc_test_lightcurves_06_chunk_16",
    "plasticc_test_lightcurves_06_chunk_17",
    "plasticc_test_lightcurves_06_chunk_18",
    "plasticc_test_lightcurves_06_chunk_19",
    "plasticc_test_lightcurves_06_chunk_20",
    "plasticc_test_lightcurves_06_chunk_21",
    "plasticc_test_lightcurves_06_chunk_22",
    "plasticc_test_lightcurves_06_chunk_23",
    "plasticc_test_lightcurves_06_chunk_24",
    "plasticc_test_lightcurves_06_chunk_25",
    "plasticc_test_lightcurves_06_chunk_26",
    "plasticc_test_lightcurves_06_chunk_27",
    "plasticc_test_lightcurves_06_chunk_28",
    "plasticc_test_lightcurves_06_chunk_29",
    "plasticc_test_lightcurves_06_chunk_30",
    "plasticc_test_lightcurves_06_chunk_31",
    "plasticc_test_lightcurves_06_chunk_32",
    "plasticc_test_lightcurves_06_chunk_33",
    "plasticc_test_lightcurves_06_chunk_34",
    "plasticc_test_lightcurves_07_chunk_0",
    "plasticc_test_lightcurves_07_chunk_1",
    "plasticc_test_lightcurves_07_chunk_2",
    "plasticc_test_lightcurves_07_chunk_3",
    "plasticc_test_lightcurves_07_chunk_4",
    "plasticc_test_lightcurves_07_chunk_5",
    "plasticc_test_lightcurves_07_chunk_6",
    "plasticc_test_lightcurves_07_chunk_7",
    "plasticc_test_lightcurves_07_chunk_8",
    "plasticc_test_lightcurves_07_chunk_9",
    "plasticc_test_lightcurves_07_chunk_10",
    "plasticc_test_lightcurves_07_chunk_11",
    "plasticc_test_lightcurves_07_chunk_12",
    "plasticc_test_lightcurves_07_chunk_13",
    "plasticc_test_lightcurves_07_chunk_14",
    "plasticc_test_lightcurves_07_chunk_15",
    "plasticc_test_lightcurves_07_chunk_16",
    "plasticc_test_lightcurves_07_chunk_17",
    "plasticc_test_lightcurves_07_chunk_18",
    "plasticc_test_lightcurves_07_chunk_19",
    "plasticc_test_lightcurves_07_chunk_20",
    "plasticc_test_lightcurves_07_chunk_21",
    "plasticc_test_lightcurves_07_chunk_22",
    "plasticc_test_lightcurves_07_chunk_23",
    "plasticc_test_lightcurves_07_chunk_24",
    "plasticc_test_lightcurves_07_chunk_25",
    "plasticc_test_lightcurves_07_chunk_26",
    "plasticc_test_lightcurves_07_chunk_27",
    "plasticc_test_lightcurves_07_chunk_28",
    "plasticc_test_lightcurves_07_chunk_29",
    "plasticc_test_lightcurves_07_chunk_30",
    "plasticc_test_lightcurves_07_chunk_31",
    "plasticc_test_lightcurves_07_chunk_32",
    "plasticc_test_lightcurves_07_chunk_33",
    "plasticc_test_lightcurves_07_chunk_34",
    "plasticc_test_lightcurves_08_chunk_0",
    "plasticc_test_lightcurves_08_chunk_1",
    "plasticc_test_lightcurves_08_chunk_2",
    "plasticc_test_lightcurves_08_chunk_3",
    "plasticc_test_lightcurves_08_chunk_4",
    "plasticc_test_lightcurves_08_chunk_5",
    "plasticc_test_lightcurves_08_chunk_6",
    "plasticc_test_lightcurves_08_chunk_7",
    "plasticc_test_lightcurves_08_chunk_8",
    "plasticc_test_lightcurves_08_chunk_9",
    "plasticc_test_lightcurves_08_chunk_10",
    "plasticc_test_lightcurves_08_chunk_11",
    "plasticc_test_lightcurves_08_chunk_12",
    "plasticc_test_lightcurves_08_chunk_13",
    "plasticc_test_lightcurves_08_chunk_14",
    "plasticc_test_lightcurves_08_chunk_15",
    "plasticc_test_lightcurves_08_chunk_16",
    "plasticc_test_lightcurves_08_chunk_17",
    "plasticc_test_lightcurves_08_chunk_18",
    "plasticc_test_lightcurves_08_chunk_19",
    "plasticc_test_lightcurves_08_chunk_20",
    "plasticc_test_lightcurves_08_chunk_21",
    "plasticc_test_lightcurves_08_chunk_22",
    "plasticc_test_lightcurves_08_chunk_23",
    "plasticc_test_lightcurves_08_chunk_24",
    "plasticc_test_lightcurves_08_chunk_25",
    "plasticc_test_lightcurves_08_chunk_26",
    "plasticc_test_lightcurves_08_chunk_27",
    "plasticc_test_lightcurves_08_chunk_28",
    "plasticc_test_lightcurves_08_chunk_29",
    "plasticc_test_lightcurves_08_chunk_30",
    "plasticc_test_lightcurves_08_chunk_31",
    "plasticc_test_lightcurves_08_chunk_32",
    "plasticc_test_lightcurves_08_chunk_33",
    "plasticc_test_lightcurves_08_chunk_34",
    "plasticc_test_lightcurves_09_chunk_0",
    "plasticc_test_lightcurves_09_chunk_1",
    "plasticc_test_lightcurves_09_chunk_2",
    "plasticc_test_lightcurves_09_chunk_3",
    "plasticc_test_lightcurves_09_chunk_4",
    "plasticc_test_lightcurves_09_chunk_5",
    "plasticc_test_lightcurves_09_chunk_6",
    "plasticc_test_lightcurves_09_chunk_7",
    "plasticc_test_lightcurves_09_chunk_8",
    "plasticc_test_lightcurves_09_chunk_9",
    "plasticc_test_lightcurves_09_chunk_10",
    "plasticc_test_lightcurves_09_chunk_11",
    "plasticc_test_lightcurves_09_chunk_12",
    "plasticc_test_lightcurves_09_chunk_13",
    "plasticc_test_lightcurves_09_chunk_14",
    "plasticc_test_lightcurves_09_chunk_15",
    "plasticc_test_lightcurves_09_chunk_16",
    "plasticc_test_lightcurves_09_chunk_17",
    "plasticc_test_lightcurves_09_chunk_18",
    "plasticc_test_lightcurves_09_chunk_19",
    "plasticc_test_lightcurves_09_chunk_20",
    "plasticc_test_lightcurves_09_chunk_21",
    "plasticc_test_lightcurves_09_chunk_22",
    "plasticc_test_lightcurves_09_chunk_23",
    "plasticc_test_lightcurves_09_chunk_24",
    "plasticc_test_lightcurves_09_chunk_25",
    "plasticc_test_lightcurves_09_chunk_26",
    "plasticc_test_lightcurves_09_chunk_27",
    "plasticc_test_lightcurves_09_chunk_28",
    "plasticc_test_lightcurves_09_chunk_29",
    "plasticc_test_lightcurves_09_chunk_30",
    "plasticc_test_lightcurves_09_chunk_31",
    "plasticc_test_lightcurves_09_chunk_32",
    "plasticc_test_lightcurves_09_chunk_33",
    "plasticc_test_lightcurves_09_chunk_34",
    "plasticc_test_lightcurves_10_chunk_0",
    "plasticc_test_lightcurves_10_chunk_1",
    "plasticc_test_lightcurves_10_chunk_2",
    "plasticc_test_lightcurves_10_chunk_3",
    "plasticc_test_lightcurves_10_chunk_4",
    "plasticc_test_lightcurves_10_chunk_5",
    "plasticc_test_lightcurves_10_chunk_6",
    "plasticc_test_lightcurves_10_chunk_7",
    "plasticc_test_lightcurves_10_chunk_8",
    "plasticc_test_lightcurves_10_chunk_9",
    "plasticc_test_lightcurves_10_chunk_10",
    "plasticc_test_lightcurves_10_chunk_11",
    "plasticc_test_lightcurves_10_chunk_12",
    "plasticc_test_lightcurves_10_chunk_13",
    "plasticc_test_lightcurves_10_chunk_14",
    "plasticc_test_lightcurves_10_chunk_15",
    "plasticc_test_lightcurves_10_chunk_16",
    "plasticc_test_lightcurves_10_chunk_17",
    "plasticc_test_lightcurves_10_chunk_18",
    "plasticc_test_lightcurves_10_chunk_19",
    "plasticc_test_lightcurves_10_chunk_20",
    "plasticc_test_lightcurves_10_chunk_21",
    "plasticc_test_lightcurves_10_chunk_22",
    "plasticc_test_lightcurves_10_chunk_23",
    "plasticc_test_lightcurves_10_chunk_24",
    "plasticc_test_lightcurves_10_chunk_25",
    "plasticc_test_lightcurves_10_chunk_26",
    "plasticc_test_lightcurves_10_chunk_27",
    "plasticc_test_lightcurves_10_chunk_28",
    "plasticc_test_lightcurves_10_chunk_29",
    "plasticc_test_lightcurves_10_chunk_30",
    "plasticc_test_lightcurves_10_chunk_31",
    "plasticc_test_lightcurves_10_chunk_32",
    "plasticc_test_lightcurves_10_chunk_33",
    "plasticc_test_lightcurves_10_chunk_34",
    "plasticc_test_lightcurves_11_chunk_0",
    "plasticc_test_lightcurves_11_chunk_1",
    "plasticc_test_lightcurves_11_chunk_2",
    "plasticc_test_lightcurves_11_chunk_3",
    "plasticc_test_lightcurves_11_chunk_4",
    "plasticc_test_lightcurves_11_chunk_5",
    "plasticc_test_lightcurves_11_chunk_6",
    "plasticc_test_lightcurves_11_chunk_7",
    "plasticc_test_lightcurves_11_chunk_8",
    "plasticc_test_lightcurves_11_chunk_9",
    "plasticc_test_lightcurves_11_chunk_10",
    "plasticc_test_lightcurves_11_chunk_11",
    "plasticc_test_lightcurves_11_chunk_12",
    "plasticc_test_lightcurves_11_chunk_13",
    "plasticc_test_lightcurves_11_chunk_14",
    "plasticc_test_lightcurves_11_chunk_15",
    "plasticc_test_lightcurves_11_chunk_16",
    "plasticc_test_lightcurves_11_chunk_17",
    "plasticc_test_lightcurves_11_chunk_18",
    "plasticc_test_lightcurves_11_chunk_19",
    "plasticc_test_lightcurves_11_chunk_20",
    "plasticc_test_lightcurves_11_chunk_21",
    "plasticc_test_lightcurves_11_chunk_22",
    "plasticc_test_lightcurves_11_chunk_23",
    "plasticc_test_lightcurves_11_chunk_24",
    "plasticc_test_lightcurves_11_chunk_25",
    "plasticc_test_lightcurves_11_chunk_26",
    "plasticc_test_lightcurves_11_chunk_27",
    "plasticc_test_lightcurves_11_chunk_28",
    "plasticc_test_lightcurves_11_chunk_29",
    "plasticc_test_lightcurves_11_chunk_30",
    "plasticc_test_lightcurves_11_chunk_31",
    "plasticc_test_lightcurves_11_chunk_32",
    "plasticc_test_lightcurves_11_chunk_33",
    "plasticc_test_lightcurves_11_chunk_34",
]

# X
X_full_test = np.load(
    f"{asnwd}/data/plasticc/test_set/full_test_transformed_df_timesteps_100_X_test_plasticc_test_lightcurves_01.npy",
)

for file in batch_filename:
    X_temp_test = np.load(
        f"{asnwd}/data/plasticc/test_set/full_test_transformed_df_timesteps_100_X_test_{file}.npy",
    )

    X_full_test = np.concatenate((X_full_test, X_temp_test), axis=0)

np.save(
    f"{asnwd}/data/plasticc/test_set/full_test_transformed_df_timesteps_100_X_full_test.npy",
    X_full_test,
)

# y
y_full_test = np.load(
    f"{asnwd}/data/plasticc/test_set/full_test_transformed_df_timesteps_100_y_test_plasticc_test_lightcurves_01.npy",
)

for file in batch_filename:
    y_temp_test = np.load(
        f"{asnwd}/data/plasticc/test_set/full_test_transformed_df_timesteps_100_y_test_{file}.npy",
    )

    y_full_test = np.concatenate((y_full_test, y_temp_test), axis=0)

np.save(
    f"{asnwd}/data/plasticc/test_set/full_test_transformed_df_timesteps_100_y_full_test.npy",
    y_full_test,
)

Z_full_test = np.load(
    f"{asnwd}/data/plasticc/test_set/full_test_transformed_df_timesteps_100_ZX_test_plasticc_test_lightcurves_01.npy",
)

for file in batch_filename:
    Z_temp_test = np.load(
        f"{asnwd}/data/plasticc/test_set/full_test_transformed_df_timesteps_100_ZX_test_{file}.npy",
    )

    Z_full_test = np.concatenate((Z_full_test, Z_temp_test), axis=0)

np.save(
    f"{asnwd}/data/plasticc/test_set/full_test_transformed_df_timesteps_100_Z_full_test.npy",
    Z_full_test,
)

print(X_full_test.shape, y_full_test.shape, Z_full_test.shape)
