name: Lint

on:
  push:
    branches:
      - master
      - issues/**
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Code quality checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout astronet
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Check formatting with black
      run: |
        uv tool run black --check --diff .

    - name: Check linting with ruff
      run: |
        uv tool run ruff check .
